# Generated by Django 4.1.3 on 2024-01-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateField(auto_now_add=True),
        ),
    ]
