# Generated by Django 4.1.3 on 2023-11-24 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materiales', '0004_alter_articulo_autor_alter_articulo_carrera_and_more'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prestamos',
            new_name='Prestamo',
        ),
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
    ]
