# Generated by Django 4.1.3 on 2024-08-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
