# Generated by Django 4.1.3 on 2024-08-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
