# Generated by Django 4.1.3 on 2024-01-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
