# Generated by Django 4.1.3 on 2024-01-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_listaespera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listaespera',
            old_name='creado_en',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='listaespera',
            old_name='usuario',
            new_name='owner',
        ),
    ]
