# Generated by Django 4.1.3 on 2024-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_rename_creado_en_listaespera_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
