# Generated by Django 4.1.3 on 2024-02-21 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_listaespera_fecha_fin_alter_prestamo_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['-fecha_fin']},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_fin']},
        ),
    ]
