# Generated by Django 4.1.3 on 2024-02-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_prestamo_options_alter_reserva_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaEspera',
        ),
    ]
