version: "3"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #command: sh -c "python manage.py runserver 0.0.0.0:8000"
    #command: daphne -b 0.0.0.0 -p 8000 bibloteca.asgi:application
    command: watchfiles --target-type=command 'daphne -b 0.0.0.0 -p 8000 bibloteca.asgi:application'
    volumes:
      - ./backend/:/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DB_HOST=db

  db:
    image: postgres:14-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis: 
    image: redis:alpine
    ports: 
      - 6379:6379

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/niginx.conf
    ports: 
     - 80:80
    depends_on:
      - django
volumes:
  postgres_data:

