version: "3"

services:
  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db

  db:
    image: postgres:15
    user: "1000:1000"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3Nano094
      - POSTGRES_DB=db

  react:
    build: 
      context: ./frontend
      args:
      - NODE_ENV=development
    environment:
      - NODE_ENV=development

    
    ports:
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./frontend:/opt/frontend/app:delegated
      - ./frontend/package.json:/opt/frontend/package.json
      - ./frontend/package-lock.json:/opt/frontend/package-lock.json
      - notused:/opt/frontend/app/node_modules
volumes:  
  postgres_data:
  notused:
