# Generated by Django 4.1.7 on 2023-04-08 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('d', 'Disponible'), ('n', 'No disponible')], help_text='Estado de Ejemplar', max_length=1, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='materiales.articulo')),
            ],
            options={
                'ordering': ['articulo'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField()),
                ('articulo', models.ManyToManyField(related_name='articulo', to='materiales.articulo')),
                ('owner', models.ManyToManyField(related_name='suario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('created_by', models.ManyToManyField(related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('ejemplar', models.ManyToManyField(related_name='Ejemplar', to='materiales.ejemplar')),
                ('usuario', models.ManyToManyField(related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_fin'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ManyToManyField(blank=True, related_name='autor', to='materiales.autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='carrera',
            field=models.ManyToManyField(blank=True, related_name='carrera', to='materiales.carrera'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='editorial',
            field=models.ManyToManyField(blank=True, related_name='editorial', to='materiales.editorial'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='genero',
            field=models.ManyToManyField(blank=True, related_name='genero', to='materiales.genero'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ManyToManyField(blank=True, related_name='tipo', to='materiales.tipomaterial'),
        ),
    ]
