# Generated by Django 4.1.3 on 2023-12-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(blank=True, choices=[(1, 'Disponible'), (0, 'No disponible')], default=1, help_text='Estado de Ejemplar', max_length=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='materiales.articulo')),
            ],
            options={
                'ordering': ['articulo'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ManyToManyField(related_name='autor', to='materiales.autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='carrera',
            field=models.ManyToManyField(related_name='carrera', to='materiales.carrera'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='editorial',
            field=models.ManyToManyField(related_name='editorial', to='materiales.editorial'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='genero',
            field=models.ManyToManyField(related_name='genero', to='materiales.genero'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.ManyToManyField(blank=True, related_name='tipo', to='materiales.tipomaterial'),
        ),
    ]
