# Generated by Django 4.1.3 on 2023-12-05 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['estado', 'articulo']},
        ),
    ]
