# Generated by Django 4.1.3 on 2024-01-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['material']},
        ),
        migrations.RemoveField(
            model_name='ejemplar',
            name='estado',
        ),
    ]
