# Generated by Django 4.1.3 on 2023-11-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Prestamos',
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
