# Generated by Django 4.1.3 on 2024-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_ejemplar_options_remove_ejemplar_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='autor',
            field=models.ManyToManyField(blank=True, related_name='autor', to='materiales.autor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='carrera',
            field=models.ManyToManyField(blank=True, related_name='carrera', to='materiales.carrera'),
        ),
        migrations.AlterField(
            model_name='material',
            name='editorial',
            field=models.ManyToManyField(blank=True, related_name='editorial', to='materiales.editorial'),
        ),
        migrations.AlterField(
            model_name='material',
            name='genero',
            field=models.ManyToManyField(blank=True, related_name='genero', to='materiales.genero'),
        ),
    ]
