# Generated by Django 4.1.3 on 2024-07-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_alter_material_autor_alter_material_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.ManyToManyField(related_name='tipo', to='materiales.tipomaterial'),
        ),
    ]
