# Generated by Django 4.1.3 on 2023-11-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_alter_ejemplar_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.ManyToManyField(related_name='autor', to='materiales.autor'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='carrera',
            field=models.ManyToManyField(related_name='carrera', to='materiales.carrera'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='editorial',
            field=models.ManyToManyField(related_name='editorial', to='materiales.editorial'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='genero',
            field=models.ManyToManyField(related_name='genero', to='materiales.genero'),
        ),
    ]
