# Generated by Django 4.1.3 on 2024-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_tolerancia', models.IntegerField(default=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
